services:
  backend:
    build:
      context: ./TICKET_DASHBOARD
      dockerfile: Dockerfile
    image: ticket-dashboard-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./TICKET_DASHBOARD/data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - ticket-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ticket-dashboard-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge

volumes:
  ticket-data: