version: '3.8'

services:
  backend:
    build: 
      context: ./TICKET_DASHBOARD
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
      - JWT_SECRET=your-secret-key-change-this-in-production
      - SUPER_TOGGLE_PWD=admin123
    volumes:
      - ./data:/app/data
    networks:
      - ticket-network

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge

volumes:
  data:
